name: great_agent_py312
channels:
  - robostack
  - conda-forge
  - defaults
dependencies:
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - icu=75.1=hfee45f7_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - liblzma=5.8.1=h39f12f2_2
  - libsqlite=3.51.0=h8adb53f_0
  - libzlib=1.3.1=h8359307_2
  - ncurses=6.5=h5e97a16_3
  - openssl=3.6.0=h5503f6c_0
  - pip=25.3=pyh8b19718_0
  - python=3.12.12=h18782d2_1_cpython
  - readline=8.2=h1d1bf99_2
  - setuptools=80.9.0=pyhff2d567_0
  - tk=8.6.13=h892fb3f_3
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - annotated-types==0.7.0
      - anyio==4.11.0
      - arrow==1.4.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.0
      - codecarbon==3.0.8
      - cryptography==46.0.3
      - distro==1.9.0
      - dotenv==0.9.9
      - fief-client==0.20.0
      - h11==0.16.0
      - httpcore==1.0.9
      - httpx==0.27.2
      - idna==3.11
      - jiter==0.12.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jwcrypto==1.5.6
      - langchain==1.0.7
      - langchain-core==1.0.5
      - langchain-openai==1.0.3
      - langgraph==1.0.3
      - langgraph-checkpoint==3.0.1
      - langgraph-prebuilt==1.0.4
      - langgraph-sdk==0.2.9
      - langsmith==0.4.43
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - numpy==2.3.4
      - nvidia-ml-py==13.580.82
      - openai==2.8.0
      - orjson==3.11.4
      - ormsgpack==1.12.0
      - packaging==25.0
      - pandas==2.3.3
      - prometheus-client==0.23.1
      - prompt-toolkit==3.0.52
      - psutil==7.1.3
      - py-cpuinfo==9.0.0
      - pycparser==2.23
      - pydantic==2.12.4
      - pydantic-core==2.41.5
      - pygments==2.19.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytz==2025.2
      - pyyaml==6.0.3
      - questionary==2.1.1
      - rapidfuzz==3.14.3
      - regex==2025.11.3
      - requests==2.32.5
      - requests-toolbelt==1.0.0
      - rich==14.2.0
      - shellingham==1.5.4
      - six==1.17.0
      - sniffio==1.3.1
      - tenacity==9.1.2
      - termcolor==3.2.0
      - tiktoken==0.12.0
      - tqdm==4.67.1
      - typer==0.20.0
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - urllib3==2.5.0
      - wcwidth==0.2.14
      - xxhash==3.6.0
      - yaspin==3.3.0
      - zstandard==0.25.0
prefix: /Users/alexrdzgarza/miniforge3/envs/great_agent_py312
